# Generated by Django 5.2.7 on 2025-11-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_1',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_2',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/'),
        ),
    ]
